@extends('layout')

@section('content')
asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
			asdddddddddddddddddddddd
@stop